debug: true

multipart:
  location: ${java.io.tmpdir}
  max-file-size: 50MB
  max-request-size: 50MB

spring:
  mvc:
    favicon:
      enabled: false

com:
  example:
    optimize: true
    gif-location: ${java.io.tmpdir}/gif
